import * as p from "@clack/prompts";
import chalk from "chalk";
import fs from "node:fs/promises";
import path from "node:path";
import { loadConfig, resolveSkillDir } from "../config.mjs";
import { listSkills, parseGptSpec } from "../parser.mjs";

export async function readmeCommand(skillName?: string): Promise<void> {
  p.intro(chalk.bgYellow.black(" agentskills readme "));

  const config = await loadConfig();
  const skills = await listSkills(config.rootDir);

  // Filter to skills with package.json
  const initialized: string[] = [];
  for (const s of skills) {
    const pkgPath = path.join(resolveSkillDir(config, s), "package.json");
    try {
      await fs.access(pkgPath);
      initialized.push(s);
    } catch {
      // skip
    }
  }

  if (initialized.length === 0) {
    p.cancel("No skills have been initialized yet. Run `agentskills init` first.");
    process.exit(1);
  }

  let selected: string;

  if (skillName && initialized.includes(skillName)) {
    selected = skillName;
  } else {
    const result = await p.select({
      message: "Select a skill to update README for",
      options: initialized.map((s) => ({ value: s, label: s })),
    });

    if (p.isCancel(result)) {
      p.cancel("Operation cancelled.");
      process.exit(0);
    }
    selected = result as string;
  }

  const skillDir = resolveSkillDir(config, selected);
  const spec = await parseGptSpec(skillDir);

  const pkgRaw = await fs.readFile(
    path.join(skillDir, "package.json"),
    "utf-8",
  );
  const pkg = JSON.parse(pkgRaw);

  // Read knowledge manifest if available
  let knowledgeSection = "";
  const manifestPath = path.join(skillDir, "knowledge-manifest.md");
  try {
    await fs.access(manifestPath);
    knowledgeSection = `
## Knowledge Files

See [knowledge-manifest.md](./knowledge-manifest.md) for the full inventory and prep instructions.
`;
  } catch {
    // no manifest
  }

  // Build files listing
  const entries = await fs.readdir(skillDir, { withFileTypes: true });
  const fileTree = entries
    .filter((e) => !e.name.startsWith(".") && e.name !== "node_modules")
    .map((e) => {
      const icon = e.isDirectory() ? "📁" : "📄";
      return `- ${icon} \`${e.name}${e.isDirectory() ? "/\`" : "\`"}`;
    })
    .join("\n");

  const readme = `# ${spec.name}

> ${spec.description}

**Version:** ${pkg.version}
**Model:** ${spec.model ?? "GPT-4o"}

## Structure

${fileTree}

## Usage

### Setup via agentskills CLI

\`\`\`bash
# Initialize this skill (creates package.json from gpt-spec.md)
agentskills init ${selected}

# Bump version after changes
agentskills bump ${selected} patch|minor|major

# Regenerate this README
agentskills readme ${selected}
\`\`\`

### Manual Setup

1. Copy the contents of [\`system-instructions.md\`](./system-instructions.md) into your GPT's **Instructions** field.
2. Upload files listed in [\`knowledge-manifest.md\`](./knowledge-manifest.md) to the GPT's **Knowledge** section.
3. Configure capabilities as specified in [\`gpt-spec.md\`](./gpt-spec.md).

## Integration

### OpenAI Custom GPT

1. Go to [chat.openai.com](https://chat.openai.com) → **Explore GPTs** → **Create**
2. Set the **Name** to \`${spec.name}\`
3. Set the **Description** to the description above
4. Paste system instructions from \`system-instructions.md\`
5. Upload knowledge files per \`knowledge-manifest.md\`
6. Configure model, capabilities, and actions per \`gpt-spec.md\`
${knowledgeSection}
## Version History

| Version | Date | Notes |
|---------|------|-------|
| ${pkg.version} | ${new Date().toISOString().split("T")[0]} | Current release |

---

*Generated by [agentskills](https://github.com/agentskills/cli) CLI*
`;

  const readmePath = path.join(skillDir, "README.md");
  await fs.writeFile(readmePath, readme, "utf-8");

  const spinner = p.spinner();
  spinner.start("Writing README.md...");
  spinner.stop(`Updated ${chalk.bold("README.md")} for ${selected}`);

  p.outro(chalk.green("Done!"));
}
